version: '3'

services:

  db:
    image: postgres:11
    container_name: postgres
    ports:
      - '5600:5432'
    environment:
      - POSTGRES_DB=weather_rep
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword
    volumes:
      - './db/init:/docker-entrypoint-initdb.d/'

  flask-api:
    container_name: app-app
    restart: always
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/usr/src/app
    depends_on:
      - "db"

  client:
    container_name: react-app
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - './frontend:/app'
      - '/app/node_modules'
    ports:
      - '3000:3000'
    depends_on:
      - "flask-api"