version: '3'

services:

  db:
    image: postgres:11
    container_name: postgres
    ports:
      - '5600:5432'
    environment:
      - POSTGRES_DB=weather_rep
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword
    volumes:
      - './db/init:/docker-entrypoint-initdb.d/'
